// frontend/src/pages/classDetail.jsx
import React, { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getClassDetail } from "../services/classes.service";
import AddMembersForm from "../components/AddMembersForm";
import { getUser } from "../auth/authStore";

export default function ClassDetail() {
  const { id } = useParams();
  const classId = Number(id);

  const [classData, setClassData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        setLoading(true);
        const data = await getClassDetail(classId);
        if (!cancelled) setClassData(data);
      } catch (e) {
        if (!cancelled) setError(e.message || "Error carregant detall");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    load();
    return () => (cancelled = true);
  }, [classId]);

  const role = useMemo(() => {
    // 1) del backend
    if (classData?.role) return classData.role;
    // 2) del user local
    const user = getUser();
    if (user?.role) return user.role;
    // 3) fallback segur
    return "ALUMNE";
  }, [classData]);

  if (loading) return <div>Carregant classe...</div>;
  if (error) return <div style={{ color: "red" }}>{error}</div>;
  if (!classData) return <div>No s’ha trobat la classe.</div>;

  // Ajusta aquestes claus segons el que et retorni el backend:
  const className = classData.name || classData.class?.name || `Classe ${classId}`;
  const members = classData.members || classData.class?.members || [];

  return (
    <div style={{ padding: 16 }}>
      <Link to="/classes">← Tornar</Link>

      <h2 style={{ marginTop: 12 }}>{className}</h2>
      <p>El teu rol: <b>{role}</b></p>

      <h3>Membres</h3>
      {members.length === 0 ? (
        <p>Encara no hi ha membres.</p>
      ) : (
        <ul>
          {members.map((m) => (
            <li key={m.id}>
              {m.name || m.email || `Usuari ${m.id}`}{" "}
              {m.role ? `(${m.role})` : ""}
            </li>
          ))}
        </ul>
      )}

      {/* Només PROFESSOR veu el formulari */}
      {role === "PROFESSOR" ? (
        <>
          <h3>Afegir membres per email</h3>
          <AddMembersForm classId={classId} />
        </>
      ) : (
        <p style={{ opacity: 0.8 }}>
          (Només el professor pot afegir membres)
        </p>
      )}
    </div>
  );
}

// web-vue-test/src/pages/ClassDetail.vue
<script setup>
import { onMounted, ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { getClassDetail } from "../services/classes.service.js";
import AddMembersForm from "../components/AddMembersForm.vue";

const route = useRoute();
const router = useRouter();

const loading = ref(false);
const error = ref("");
const detail = ref(null);

async function load() {
  loading.value = true;
  error.value = "";
  try {
    const res = await getClassDetail(route.params.id);
    detail.value = res.data;
  } catch (e) {
    error.value = e.message || "Error carregant detall";
  } finally {
    loading.value = false;
  }
}

onMounted(load);
</script>

<template>
  <div>
    <button @click="router.push('/classes')">← Tornar</button>

    <p v-if="loading">Carregant...</p>
    <p v-if="error" style="color:red">{{ error }}</p>

    <div v-if="detail">
      <h3>{{ detail.nom }}</h3>
      <p>Rol: <b>{{ detail.role }}</b></p>

      <h4>Membres</h4>
      <ul>
        <li v-for="m in detail.members" :key="m.id">
          {{ m.email }} ({{ m.rol }})
        </li>
      </ul>

      <div v-if="detail.role === 'PROFESSOR'" style="margin-top: 16px">
        <h4>Afegir membres</h4>
        <AddMembersForm :classId="detail.id" />
      </div>

      <p v-else style="opacity: 0.7; margin-top: 12px">
        Només el professor pot afegir membres.
      </p>
    </div>
  </div>
</template>
