// web-vue-test/src/pages/ClassesList.vue
<script setup>
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { getClasses } from "../services/classes.service.js";

const router = useRouter();
const loading = ref(false);
const error = ref("");
const classes = ref([]);

async function load() {
  loading.value = true;
  error.value = "";
  try {
    const res = await getClasses();
    classes.value = res.data || [];
  } catch (e) {
    error.value = e.message || "Error carregant classes";
  } finally {
    loading.value = false;
  }
}

function goToClass(id) {
  router.push(`/classes/${id}`);
}

onMounted(load);
</script>

<template>
  <div>
    <h3>Llista de classes</h3>

    <p v-if="loading">Carregant...</p>
    <p v-if="error" style="color:red">{{ error }}</p>

    <p v-if="!loading && classes.length === 0">No tens classes encara.</p>

    <ul v-if="classes.length">
      <li v-for="c in classes" :key="c.id" style="margin-bottom: 8px">
        <button @click="goToClass(c.id)">
          {{ c.nom || c.name || c.id }}
        </button>
      </li>
    </ul>
  </div>
</template>

// frontend/src/pages/classesList.jsx
import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getClasses } from "../services/classes.service";

export default function ClassesList() {
  const [classes, setClasses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        setLoading(true);
        const data = await getClasses();
        if (!cancelled) setClasses(data || []);
      } catch (e) {
        if (!cancelled) setError(e.message || "Error carregant classes");
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    load();
    return () => (cancelled = true);
  }, []);

  if (loading) return <div>Carregant classes...</div>;
  if (error) return <div style={{ color: "red" }}>{error}</div>;

  return (
    <div style={{ padding: 16 }}>
      <h2>Classes</h2>

      {classes.length === 0 ? (
        <p>Encara no formes part de cap classe.</p>
      ) : (
        <ul>
          {classes.map((c) => (
            <li key={c.id}>
              <Link to={`/classes/${c.id}`}>{c.name || `Classe ${c.id}`}</Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
